refactor(shell): migrate shell scripts from zsh to bash
- Convert delta_ and git-continue from zsh to bash
- Fix shellcheck warnings in git-st
- Remove unused scripts (git-ctags, test-drive)
- Update togglemode file permissions

diff --git a/config/zsh.d/zsh/bin/git-continue b/config/zsh.d/zsh/bin/git-continue
--- a/config/zsh.d/zsh/bin/git-continue
+++ b/config/zsh.d/zsh/bin/git-continue
@@ -1,4 +1,4 @@
-#!/usr/bin/env zsh
+#!/usr/bin/env bash
 
 # Runs `git rebase --continue`, `git cherry-pick --continue` as appropriate,
 # based on context.
@@ -8,20 +8,20 @@
 GIT_DIR=$(git rev-parse --git-dir)
 
 if [ $? -ne 0 ]; then
-    exit $?
+	exit $?
 fi
 
 if [ -d "${GIT_DIR}/rebase-merge" ]; then
-    git rebase --continue
+	git rebase --continue
 elif [ -d "${GIT_DIR}/rebase-apply" ]; then
-    git rebase --continue
+	git rebase --continue
 elif [ -f "${GIT_DIR}/MERGE_HEAD" ]; then
-    git merge --continue
+	git merge --continue
 elif [ -f "${GIT_DIR}/CHERRY_PICK_HEAD" ]; then
-    git cherry-pick --continue
+	git cherry-pick --continue
 elif [ -f "${GIT_DIR}/REVERT_HEAD" ]; then
-    git revert --continue
+	git revert --continue
 else
-    echo "error: No operation to --continue"
-    exit 1
+	echo "error: No operation to --continue"
+	exit 1
 fi
